# -*- coding: utf-8 -*-
"""OCR_Documentos_Notaria_SantaCruz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vX6Isw03ZvRfhaZWwNooq1FE9KYwmLeg
"""

"""
═══════════════════════════════════════════════════════════════════════
🔥 SISTEMA OCR INTELIGENTE PARA NOTARÍA SANTA CRUZ
═══════════════════════════════════════════════════════════════════════

Autor: TeAmoHachi
Fecha: 2025-01-14
Versión: 1.0

DOCUMENTOS SOPORTADOS:
✅ DNI Azul (formato antiguo)
✅ DNI Electrónico (formato nuevo)
✅ Carnet de Extranjería
✅ Pasaporte Peruano
✅ Pasaporte Extranjero

REQUISITOS:
- Google Colab Pro (GPU activada)
- Python 3.10+
- PaddleOCR
- OpenCV

═══════════════════════════════════════════════════════════════════════
"""

# ═══════════════════════════════════════════════════════════════════════
# PASO 1: VERIFICAR GPU (Colab Pro)
# ═══════════════════════════════════════════════════════════════════════

import subprocess
import sys

print("🔍 Verificando GPU disponible...")
print("=" * 70)

# Verificar NVIDIA GPU
try:
    gpu_info = subprocess.check_output(['nvidia-smi'], encoding='utf-8')
    print("✅ GPU DETECTADA:")
    print(gpu_info)
except:
    print("⚠️ NO SE DETECTÓ GPU")
    print("💡 SOLUCIÓN:")
    print("   1. Ve a: Entorno de ejecución → Cambiar tipo de entorno")
    print("   2. Selecciona: Acelerador de hardware → T4 GPU")
    print("   3. Guarda y vuelve a ejecutar esta celda")
    sys.exit(1)

print("\n✅ GPU lista para usar")

# ═══════════════════════════════════════════════════════════════════════
# PASO 2: INSTALAR DEPENDENCIAS (VERSIONES FIJAS Y ESTABLES)
# ═══════════════════════════════════════════════════════════════════════

print("📦 Instalando librerías con versiones compatibles...")
print("=" * 70)

# ═══════════════════════════════════════════════════════════════════════
# PASO 1: LIMPIAR INSTALACIONES PREVIAS
# ═══════════════════════════════════════════════════════════════════════

print("\n🧹 Limpiando instalaciones previas...")
!pip uninstall -y -q paddlepaddle paddlepaddle-gpu paddleocr paddlex 2>/dev/null
print("   ✅ Limpieza completada")

# ═══════════════════════════════════════════════════════════════════════
# PASO 2: INSTALAR NUMPY CORRECTO (CRÍTICO)
# ═══════════════════════════════════════════════════════════════════════

print("\n🔧 Instalando NumPy 1.26.4 (compatible)...")
!pip install -q "numpy<2.0" --force-reinstall
print("   ✅ NumPy 1.26.4 instalado")

# ═══════════════════════════════════════════════════════════════════════
# PASO 3: INSTALAR PADDLEPADDLE 2.6.1 (VERSIÓN ESTABLE)
# ═══════════════════════════════════════════════════════════════════════

print("\n🔧 Instalando PaddlePaddle 2.6.1...")
!pip install -q paddlepaddle-gpu==2.6.1
print("   ✅ PaddlePaddle 2.6.1 instalado")

# ═══════════════════════════════════════════════════════════════════════
# PASO 4: INSTALAR PADDLEOCR 2.7.3 (COMPATIBLE CON 2.6.1)
# ═══════════════════════════════════════════════════════════════════════

print("\n🔧 Instalando PaddleOCR 2.7.3...")
!pip install -q paddleocr==2.7.3
print("   ✅ PaddleOCR 2.7.3 instalado")

# ═══════════════════════════════════════════════════════════════════════
# PASO 5: INSTALAR DEPENDENCIAS
# ═══════════════════════════════════════════════════════════════════════

print("\n🔧 Instalando OpenCV y dependencias...")
!pip install -q opencv-python-headless pillow shapely
print("   ✅ OpenCV instalado")

# ═══════════════════════════════════════════════════════════════════════
# PASO 6: REINICIAR KERNEL (OBLIGATORIO)
# ═══════════════════════════════════════════════════════════════════════

print("\n" + "=" * 70)
print("✅ INSTALACIÓN COMPLETADA")
print("=" * 70)

print("\n🔄 REINICIANDO KERNEL...")
print("   ⏱️ Se reiniciará en 3 segundos...")
print("\n💡 DESPUÉS DEL REINICIO (mensaje 'session crashed'):")
print("   1. Click en RECONNECT")
print("   2. Ejecuta celda 1 (verificar GPU)")
print("   3. Ejecuta celda 2B (verificación)")
print("   4. Ejecuta celda 3 (inicializar OCR)")

import time
time.sleep(3)

import os
os.kill(os.getpid(), 9)

# ═══════════════════════════════════════════════════════════════════════
# CELDA 2A: INSTALAR NUMPY Y REINICIAR (PASO 1 de 2)
# ═══════════════════════════════════════════════════════════════════════

print("📦 PASO 1: Instalando NumPy correcto...")
print("=" * 70)

# Limpiar versiones conflictivas
print("\n🧹 Limpiando NumPy anterior...")
!pip uninstall -y -q numpy 2>/dev/null

# Instalar NumPy 1.26.4
print("\n🔧 Instalando NumPy 1.26.4...")
!pip install -q "numpy==1.26.4"

# Verificar instalación
import numpy as np
print(f"\n✅ NumPy instalado: {np.__version__}")

if not np.__version__.startswith('1.26'):
    print("   ⚠️ Versión incorrecta, reintentando...")
    !pip install --force-reinstall -q "numpy==1.26.4"

print("\n" + "=" * 70)
print("✅ NUMPY 1.26.4 INSTALADO")
print("=" * 70)

print("\n🔄 REINICIANDO KERNEL...")
print("   Esto es OBLIGATORIO para que NumPy se cargue correctamente")
print("\n💡 DESPUÉS DEL REINICIO:")
print("   1. Click en RECONNECT")
print("   2. ⚠️ NO ejecutes celda 2A de nuevo")
print("   3. ✅ Ejecuta celda 2B (instalar PaddleOCR)")

import time
time.sleep(3)

import os
os.kill(os.getpid(), 9)

# ═══════════════════════════════════════════════════════════════════════
# CELDA 2B: INSTALAR PADDLEOCR (VERSIÓN MEJORADA - congela NumPy)
# ═══════════════════════════════════════════════════════════════════════

print("📦 PASO 2: Instalando PaddleOCR con NumPy congelado...")
print("=" * 70)

# ═══════════════════════════════════════════════════════════════════════
# Verificar NumPy inicial
# ═══════════════════════════════════════════════════════════════════════

import numpy as np
print(f"\n🔍 NumPy inicial: {np.__version__}")

if not np.__version__.startswith('1.26'):
    print("   ❌ ERROR: NumPy incorrecto")
    print("   Ejecuta celda 2A y reinicia nuevamente")
    raise Exception("NumPy incorrecto")
else:
    print("   ✅ NumPy 1.26.4 correcto")

# ═══════════════════════════════════════════════════════════════════════
# Crear constraints.txt para BLOQUEAR NumPy
# ═══════════════════════════════════════════════════════════════════════

print("\n🔒 Creando restricciones para evitar upgrade de NumPy...")

with open('/tmp/constraints.txt', 'w') as f:
    f.write('numpy==1.26.4\n')
    f.write('scipy<1.14.0\n')  # Versión compatible con NumPy 1.x

print("   ✅ Restricciones creadas")

# ═══════════════════════════════════════════════════════════════════════
# Instalar PaddlePaddle (sin dependencias)
# ═══════════════════════════════════════════════════════════════════════

print("\n🔧 Instalando PaddlePaddle 2.6.1...")
!pip install -q --no-deps paddlepaddle-gpu==2.6.1
!pip install -q -c /tmp/constraints.txt protobuf decorator astor
print("   ✅ PaddlePaddle instalado")

# ═══════════════════════════════════════════════════════════════════════
# Instalar PaddleOCR (con restricciones de NumPy)
# ═══════════════════════════════════════════════════════════════════════

print("\n🔧 Instalando PaddleOCR 2.7.3 con restricciones...")
!pip install -q --no-deps paddleocr==2.7.3
!pip install -q -c /tmp/constraints.txt \
    opencv-python-headless pillow shapely pyclipper lmdb tqdm \
    rapidfuzz pyyaml attrdict scipy scikit-image imgaug

print("   ✅ PaddleOCR instalado")

# ═══════════════════════════════════════════════════════════════════════
# Verificar que NumPy NO cambió
# ═══════════════════════════════════════════════════════════════════════

print("\n🔍 Verificando que NumPy no cambió...")
import importlib
importlib.reload(np)
import numpy as np

print(f"   NumPy final: {np.__version__}")

if not np.__version__.startswith('1.26'):
    print("   ❌ NumPy cambió a 2.x")
    print("   Forzando downgrade...")
    !pip install --force-reinstall -q "numpy==1.26.4"
    print("   ✅ NumPy restaurado")
else:
    print("   ✅ NumPy se mantuvo en 1.26.4")

# ═══════════════════════════════════════════════════════════════════════
# Verificación final
# ═══════════════════════════════════════════════════════════════════════

print("\n" + "=" * 70)
print("🔍 VERIFICANDO INSTALACIÓN FINAL")
print("=" * 70)

try:
    import paddle
    print(f"\n✅ PaddlePaddle: {paddle.__version__}")
except Exception as e:
    print(f"❌ Error: {e}")

try:
    import paddleocr
    print(f"✅ PaddleOCR: {paddleocr.__version__}")
except Exception as e:
    print(f"❌ Error: {e}")

try:
    import cv2
    print(f"✅ OpenCV: {cv2.__version__}")
except Exception as e:
    print(f"❌ Error: {e}")

print(f"✅ NumPy: {np.__version__}")

print("\n" + "=" * 70)
print("✅ INSTALACIÓN COMPLETA")
print("=" * 70)
print("\n💡 Ahora ejecuta la celda 3 (Inicializar OCR)")

# ═══════════════════════════════════════════════════════════════════════
# CELDA 2C: ARREGLAR SCIPY (opcional, solo si celda 3 falla)
# ═══════════════════════════════════════════════════════════════════════

print("🔧 Arreglando scipy...")

# Desinstalar scipy corrupto
!pip uninstall -y scipy 2>/dev/null

# Reinstalar scipy compatible con NumPy 1.26.4
!pip install -q "scipy==1.11.4"

print("✅ Scipy reinstalado")

# Verificar
try:
    import scipy
    print(f"✅ Scipy: {scipy.__version__}")
except Exception as e:
    print(f"⚠️ Scipy sigue con error: {e}")
    print("   Pero PaddleOCR puede funcionar igual")

# ═══════════════════════════════════════════════════════════════════════
# PASO 3: INICIALIZAR OCR (compatible con PaddleOCR 2.7.3)
# ═══════════════════════════════════════════════════════════════════════

print("🤖 Inicializando motor OCR...")
print("=" * 70)
print("⏱️ Descargando modelos (solo la primera vez)...\n")

from paddleocr import PaddleOCR

# Configuración compatible con PaddleOCR 2.7.3
ocr_engine = PaddleOCR(
    use_angle_cls=True,  # Detectar orientación
    lang='es'            # Idioma español
)

print("\n✅ Motor OCR listo")
print("   🇪🇸 Idioma: Español")
print("   🎯 Versión 2.7.3 (estable)")
print("   ⚡ GPU activada automáticamente")

# ═══════════════════════════════════════════════════════════════════════
# FUNCIONES AUXILIARES
# ═══════════════════════════════════════════════════════════════════════

def extraer_texto_limpio(resultado_ocr):
    """
    Convierte el resultado de PaddleOCR a texto plano limpio

    Args:
        resultado_ocr: Output de ocr.ocr()

    Returns:
        str: Texto extraído limpio
    """
    if not resultado_ocr or not resultado_ocr[0]:
        return ""

    lineas = []
    for linea in resultado_ocr[0]:
        texto = linea[1][0]  # [1][0] = texto detectado
        confianza = linea[1][1]  # [1][1] = confianza (0-1)

        # Solo incluir texto con confianza > 60%
        if confianza > 0.6:
            lineas.append(texto)

    return "\n".join(lineas)


def mostrar_resultado_ocr(resultado_ocr, titulo="Texto Extraído"):
    """
    Muestra el resultado del OCR de forma bonita
    """
    print(f"\n{'=' * 70}")
    print(f"📄 {titulo}")
    print(f"{'=' * 70}\n")

    if not resultado_ocr or not resultado_ocr[0]:
        print("❌ No se detectó texto")
        return

    for i, linea in enumerate(resultado_ocr[0], 1):
        texto = linea[1][0]
        confianza = linea[1][1]

        # Color según confianza
        if confianza > 0.9:
            emoji = "✅"
        elif confianza > 0.7:
            emoji = "⚠️"
        else:
            emoji = "❌"

        print(f"{emoji} [{confianza*100:5.1f}%] {texto}")

    print(f"\n{'=' * 70}")


def mejorar_imagen_para_ocr(imagen):
    """
    Mejora fotocopias y fotos de baja calidad

    Aplica:
    - Conversión a escala de grises
    - Aumento de contraste (CLAHE)
    - Reducción de ruido
    - Binarización adaptativa
    - Aumento de nitidez

    Args:
        imagen: numpy array (BGR)

    Returns:
        numpy array: Imagen mejorada
    """
    # 1) Convertir a escala de grises
    if len(imagen.shape) == 3:
        gray = cv2.cvtColor(imagen, cv2.COLOR_BGR2GRAY)
    else:
        gray = imagen

    # 2) Aumentar contraste (hace el texto más visible)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    enhanced = clahe.apply(gray)

    # 3) Reducir ruido (suaviza manchas de fotocopia)
    denoised = cv2.fastNlMeansDenoising(enhanced, h=10)

    # 4) Binarización adaptativa (texto negro sobre blanco)
    binary = cv2.adaptiveThreshold(
        denoised,
        255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY,
        11,
        2
    )

    # 5) Aumentar nitidez
    kernel = np.array([[-1, -1, -1],
                       [-1,  9, -1],
                       [-1, -1, -1]])
    sharpened = cv2.filter2D(binary, -1, kernel)

    return sharpened


def cargar_imagen(ruta_o_bytes):
    """
    Carga imagen desde archivo o bytes

    Args:
        ruta_o_bytes: str (ruta) o bytes (archivo subido)

    Returns:
        numpy array: Imagen en formato BGR
    """
    if isinstance(ruta_o_bytes, str):
        # Es una ruta de archivo
        imagen = cv2.imread(ruta_o_bytes)
    else:
        # Es bytes (archivo subido en Streamlit/Colab)
        imagen = cv2.imdecode(
            np.frombuffer(ruta_o_bytes.read(), np.uint8),
            cv2.IMREAD_COLOR
        )

    return imagen


def detectar_calidad_imagen(imagen):
    """
    Evalúa la calidad de la imagen

    Returns:
        dict: {
            "contraste": float,
            "nitidez": float,
            "es_fotocopia": bool,
            "calidad": str ("EXCELENTE" | "BUENA" | "REGULAR" | "MALA")
        }
    """
    # Convertir a gris si es necesario
    if len(imagen.shape) == 3:
        gray = cv2.cvtColor(imagen, cv2.COLOR_BGR2GRAY)
    else:
        gray = imagen

    # Calcular contraste (desviación estándar)
    contraste = gray.std()

    # Calcular nitidez (Laplacian variance)
    laplacian = cv2.Laplacian(gray, cv2.CV_64F)
    nitidez = laplacian.var()

    # Determinar si es fotocopia (bajo contraste)
    es_fotocopia = contraste < 50

    # Clasificar calidad
    if contraste > 60 and nitidez > 500:
        calidad = "EXCELENTE"
    elif contraste > 45 and nitidez > 300:
        calidad = "BUENA"
    elif contraste > 30:
        calidad = "REGULAR"
    else:
        calidad = "MALA"

    return {
        "contraste": contraste,
        "nitidez": nitidez,
        "es_fotocopia": es_fotocopia,
        "calidad": calidad
    }


print("✅ Funciones auxiliares cargadas")

# ═══════════════════════════════════════════════════════════════════════
# DETECTORES DE TIPO DE DOCUMENTO (VERSIÓN MEJORADA)
# ═══════════════════════════════════════════════════════════════════════

import re

def limpiar_texto_ocr(texto):
    """
    Limpia texto del OCR para mejorar detección
    - Elimina espacios extra
    - Normaliza caracteres especiales
    - Convierte a mayúsculas
    """
    # Mayúsculas
    texto = texto.upper()

    # Reemplazar caracteres similares
    texto = texto.replace('Ú', 'U')
    texto = texto.replace('É', 'E')
    texto = texto.replace('Á', 'A')
    texto = texto.replace('Í', 'I')
    texto = texto.replace('Ó', 'O')
    texto = texto.replace('Ñ', 'N')

    # Eliminar espacios múltiples
    texto = re.sub(r'\s+', ' ', texto)

    return texto


def detectar_tipo_documento(texto_ocr):
    """
    Detecta el tipo de documento automáticamente (VERSIÓN MEJORADA)

    Mejoras:
    - Búsqueda flexible (sin acentos, sin espacios exactos)
    - Scoring ponderado (múltiples palabras clave)
    - Maneja errores comunes del OCR
    """
    texto = limpiar_texto_ocr(texto_ocr)

    # ═══════════════════════════════════════════════════════
    # PALABRAS CLAVE POR TIPO (sin acentos, flexibles)
    # ═══════════════════════════════════════════════════════

    patterns = {
        "DNI_AZUL": {
            "palabras": [
                "DOCUMENTO NACIONAL DE IDENTIDAD",
                "DOCUMENTONACIONALDE IDENTIDAD",  # Sin espacios
                "REPUBLICA DEL PERU",
                "REPUBLICADEL PERU",  # Sin espacio
                "CUI",
                "CONSTANCIA DE SUFRAGIO",
                "CONSTANCIADE SUFRAGIO"
            ],
            "score_minimo": 3  # Necesita al menos 3 matches
        },

        "DNI_ELECTRONICO": {
            "palabras": [
                "DOCUMENTO NACIONAL DE IDENTIDAD",
                "DOCUMENTONACIONALDE IDENTIDAD",
                "REPUBLICA DEL PERU",
                "REPUBLICADEL PERU",
                "REGISTRO NACIONAL",
                "REGISTRONACIONAL",
                "CUI",
                "PRIMER APELLIDO",
                "PRIMERAPELLIDO",
                "SEGUNDO APELLIDO",
                "SEGUNDOAPELLIDO",
                "PRENOMBRES",
                "CONSTANCIA",
                # NO debe tener estas palabras (diferenciador)
                "!SUPERINTENDENCIA"  # ! = NO debe estar
            ],
            "score_minimo": 4
        },

        "CARNET_EXTRANJERIA": {
            "palabras": [
                "SUPERINTENDENCIA NACIONAL DE MIGRACIONES",
                "SUPERINTENDENCIANACIONAL DEMIGRACIONES",
                "CARNE DE EXTRANJERIA",
                "CARNEDE EXTRANJERIA",
                "CALIDAD MIGRATORIA",
                "CALIDADMIGRATORIA",
                "MIGRACIONES PERU",
                "MIGRACIONESPERU"
            ],
            "score_minimo": 2
        },

        "PASAPORTE_PERUANO": {
            "palabras": [
                "PASSPORT",
                "PASAPORTE",
                "REPUBLICA DEL PERU",
                "REPUBLICADEL PERU",
                "P<PER",
                "TYPE P",
                "TIPO P"
            ],
            "score_minimo": 2
        },

        "PASAPORTE_EXTRANJERO": {
            "palabras": [
                "PASSPORT",
                "PASSEPORT",
                "P<USA", "P<ESP", "P<ARG", "P<COL", "P<VEN",
                "P<CHL", "P<BRA", "P<ECU", "P<BOL", "P<MEX"
            ],
            "score_minimo": 1
        }
    }

    # ═══════════════════════════════════════════════════════
    # CALCULAR SCORES
    # ═══════════════════════════════════════════════════════

    scores = {}

    for tipo, config in patterns.items():
        score = 0

        for palabra in config["palabras"]:
            # Palabras negativas (no deben estar)
            if palabra.startswith("!"):
                palabra_limpia = palabra[1:]
                if palabra_limpia in texto:
                    score -= 10  # Penalización fuerte
            else:
                # Palabras positivas (deben estar)
                if palabra in texto:
                    score += 1

        scores[tipo] = score

    # ═══════════════════════════════════════════════════════
    # DETERMINAR TIPO GANADOR
    # ═══════════════════════════════════════════════════════

    # Ordenar por score
    tipos_ordenados = sorted(scores.items(), key=lambda x: x[1], reverse=True)

    mejor_tipo, mejor_score = tipos_ordenados[0]
    score_minimo = patterns[mejor_tipo]["score_minimo"]

    # Verificar si cumple el mínimo
    if mejor_score >= score_minimo:

        # Mapear colores y formatos
        info_tipos = {
            "DNI_AZUL": {
                "formato": "ANTIGUO",
                "color": "AZUL_TURQUESA",
                "pais": "PERU"
            },
            "DNI_ELECTRONICO": {
                "formato": "NUEVO",
                "color": "BEIGE_CREMA",
                "pais": "PERU"
            },
            "CARNET_EXTRANJERIA": {
                "formato": "MIGRACIONES",
                "color": "ROSA_AMARILLO",
                "pais": "PERU"
            },
            "PASAPORTE_PERUANO": {
                "formato": "PASAPORTE",
                "color": "VINO_TINTO",
                "pais": "PERU"
            },
            "PASAPORTE_EXTRANJERO": {
                "formato": "PASAPORTE",
                "color": "VARIA",
                "pais": "EXTRANJERO"
            }
        }

        info = info_tipos[mejor_tipo]
        confianza = min(mejor_score / (score_minimo + 2), 1.0)  # Normalizar 0-1

        return {
            "tipo": mejor_tipo,
            "formato": info["formato"],
            "color": info["color"],
            "pais": info["pais"],
            "confianza": confianza,
            "score": mejor_score,
            "debug_scores": scores  # Para debugging
        }

    # No se pudo identificar
    return {
        "tipo": "DESCONOCIDO",
        "formato": None,
        "color": None,
        "pais": None,
        "confianza": 0.0,
        "score": mejor_score,
        "debug_scores": scores
    }


def mostrar_deteccion(deteccion):
    """
    Muestra el resultado de detección de forma visual
    """
    print(f"\n{'=' * 70}")
    print("🔍 DETECCIÓN DE DOCUMENTO")
    print(f"{'=' * 70}\n")

    tipo = deteccion["tipo"]
    confianza = deteccion["confianza"]

    if tipo == "DESCONOCIDO":
        print("❌ NO SE PUDO IDENTIFICAR EL DOCUMENTO")
        print("\n📊 Scores de detección (debug):")
        for t, s in deteccion["debug_scores"].items():
            print(f"   {t}: {s} puntos")
        print("\n💡 Posibles causas:")
        print("   - Imagen muy borrosa")
        print("   - Documento parcialmente visible")
        print("   - Tipo de documento no soportado")
        return

    # Emoji según tipo
    emojis = {
        "DNI_AZUL": "🔵",
        "DNI_ELECTRONICO": "🆕",
        "CARNET_EXTRANJERIA": "🌍",
        "PASAPORTE_PERUANO": "🇵🇪",
        "PASAPORTE_EXTRANJERO": "🛂"
    }

    emoji = emojis.get(tipo, "📄")

    print(f"{emoji} TIPO: {tipo.replace('_', ' ')}")
    print(f"📊 CONFIANZA: {confianza*100:.1f}%")
    print(f"📊 SCORE: {deteccion['score']} puntos")
    print(f"🎨 COLOR: {deteccion.get('color', 'N/A')}")
    print(f"🌎 PAÍS: {deteccion.get('pais', 'N/A')}")

    # Mostrar scores de debug
    print(f"\n📊 Scores de todos los tipos:")
    for t, s in deteccion["debug_scores"].items():
        simbolo = "✅" if t == tipo else "  "
        print(f"   {simbolo} {t}: {s} puntos")

    # Indicar si necesita reverso
    necesita_reverso = tipo in ["DNI_AZUL", "DNI_ELECTRONICO", "CARNET_EXTRANJERIA"]

    if necesita_reverso:
        print(f"\n⚠️  REQUIERE FOTO DEL REVERSO")
        print("   (Para obtener dirección completa)")
    else:
        print(f"\n✅ NO REQUIERE REVERSO")
        print("   (Todos los datos están en una sola página)")

    print(f"\n{'=' * 70}")


print("✅ Detector de documentos mejorado (v2.0)")

# ═══════════════════════════════════════════════════════════════════════
# PARSER 1: DNI (VERSIÓN v4.4 - ESTADO CIVIL CORREGIDO)
# ═══════════════════════════════════════════════════════════════════════

def parsear_dni(texto_ocr, tipo_dni="DNI_AZUL"):
    """
    Extrae campos de DNI con estado civil corregido
    """
    import re
    datos = {}

    lineas = [l.strip() for l in texto_ocr.split('\n') if l.strip()]

    def buscar_indice(palabra_clave):
        for i, linea in enumerate(lineas):
            if re.search(palabra_clave, linea, re.IGNORECASE):
                return i
        return -1

    # ═══════════════════════════════════════════════════════
    # CUI Y DNI
    # ═══════════════════════════════════════════════════════

    cui_match = re.search(r'CUI[:\s]*(\d{8}[-\s]?\d)', texto_ocr, re.IGNORECASE)
    if cui_match:
        cui_completo = cui_match.group(1).replace(' ', '-')
        datos["cui"] = cui_completo
        datos["dni"] = cui_completo.split("-")[0]

    if "dni" not in datos:
        dni_matches = re.findall(r'\b(\d{8})\b', texto_ocr)
        for match in dni_matches:
            if not match.startswith(('01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31')):
                datos["dni"] = match
                break

    # ═══════════════════════════════════════════════════════
    # APELLIDOS
    # ═══════════════════════════════════════════════════════

    idx_ap1 = buscar_indice(r'Primer\s*Apellido')
    if idx_ap1 >= 0 and idx_ap1 + 1 < len(lineas):
        datos["apellido_paterno"] = lineas[idx_ap1 + 1]

    idx_ap2 = buscar_indice(r'Segundo\s*Apellido')
    if idx_ap2 >= 0 and idx_ap2 + 1 < len(lineas):
        datos["apellido_materno"] = lineas[idx_ap2 + 1]

    # ═══════════════════════════════════════════════════════
    # PRENOMBRES
    # ═══════════════════════════════════════════════════════

    idx_prenombres = buscar_indice(r'Prenombres?')

    if idx_prenombres >= 0:
        for i in range(idx_prenombres - 1, max(idx_prenombres - 4, -1), -1):
            linea = lineas[i]
            if re.match(r'^[A-ZÁÉÍÓÚÑ\s]{10,}$', linea):
                if linea not in [datos.get("apellido_paterno"), datos.get("apellido_materno")]:
                    if not re.search(r'(Apellido|BENAVENTE|RIVADENEIRA|REGISTRO|REPUBLICA)', linea, re.IGNORECASE):
                        nombres = linea

                        if len(nombres.replace(' ', '')) > 15:
                            nombres = re.sub(
                                r'(MARIA|MONICA|MILAGROS|JUAN|JOSE|LUIS|CARLOS|PEDRO|ANA|ROSA|CARMEN|TERESA|ISABEL|GLORIA|PATRICIA|ALEJANDRA|FERNANDA|CAROLINA|DANIELA|ANDREA|CLAUDIA|VALENTINA|SOFIA|CAMILA|GABRIELA)',
                                r'\1 ',
                                nombres
                            ).strip()

                        nombres = re.sub(r'\s+', ' ', nombres)
                        datos["nombres"] = nombres
                        break

    if all(k in datos for k in ["nombres", "apellido_paterno", "apellido_materno"]):
        datos["nombre_completo"] = (
            f"{datos['nombres']} "
            f"{datos['apellido_paterno']} "
            f"{datos['apellido_materno']}"
        )

    # ═══════════════════════════════════════════════════════
    # FECHA DE NACIMIENTO
    # ═══════════════════════════════════════════════════════

    fnac_match = re.search(r'\b([0-3]\d)([0-1]\d)(19\d{2}|20[0-2]\d)\b', texto_ocr)
    if fnac_match:
        dia, mes, anio = fnac_match.groups()
        datos["fecha_nacimiento"] = f"{dia}/{mes}/{anio}"
        datos["fecha_nacimiento_iso"] = f"{anio}-{mes}-{dia}"

        from datetime import datetime
        try:
            hoy = datetime.now()
            fecha_nac = datetime(int(anio), int(mes), int(dia))
            edad = (hoy - fecha_nac).days // 365
            datos["edad"] = edad
        except:
            pass

    # ═══════════════════════════════════════════════════════
    # SEXO
    # ═══════════════════════════════════════════════════════

    sexo_match = re.search(r'Sexo[:\s]*\n?\s*([MF])\b', texto_ocr, re.IGNORECASE)
    if sexo_match:
        datos["sexo"] = sexo_match.group(1).upper()
        datos["sexo_completo"] = "MASCULINO" if datos["sexo"] == "M" else "FEMENINO"

    # ═══════════════════════════════════════════════════════
    # NACIONALIDAD
    # ═══════════════════════════════════════════════════════

    nac_match = re.search(r'Nacionalidad[:\s]*\n?\s*([A-Z]{3})\b', texto_ocr, re.IGNORECASE)
    if nac_match:
        codigo = nac_match.group(1).upper()
        datos["nacionalidad"] = "PERUANA" if codigo == "PER" else codigo

    # ═══════════════════════════════════════════════════════
    # ESTADO CIVIL (CORREGIDO)
    # ═══════════════════════════════════════════════════════

    estados_validos = ["SOLTERO", "SOLTERA", "CASADO", "CASADA", "DIVORCIADO", "DIVORCIADA", "VIUDO", "VIUDA"]

    # Estrategia 1: Buscar cerca de "Estado Civil"
    idx_estado = buscar_indice(r'Estado\s*Civil')
    if idx_estado >= 0:
        # Buscar en las siguientes 3 líneas
        for i in range(idx_estado + 1, min(idx_estado + 4, len(lineas))):
            candidato = lineas[i].upper().strip()
            if candidato in estados_validos:
                datos["estado_civil"] = candidato
                break

    # Estrategia 2: Buscar directamente en todo el texto
    if "estado_civil" not in datos:
        texto_upper = texto_ocr.upper()
        for estado in estados_validos:
            if estado in texto_upper:
                datos["estado_civil"] = estado
                break

    # ═══════════════════════════════════════════════════════
    # FECHAS DE EMISIÓN Y CADUCIDAD
    # ═══════════════════════════════════════════════════════

    idx_emision = buscar_indice(r'Emisi[oó]n')
    if idx_emision >= 0 and idx_emision + 1 < len(lineas):
        emision_str = lineas[idx_emision + 1]
        if re.match(r'^\d{8}$', emision_str):
            dia = emision_str[0:2]
            mes = emision_str[2:4]
            anio = emision_str[4:8]
            datos["fecha_emision"] = f"{dia}/{mes}/{anio}"

    idx_cad = buscar_indice(r'Caducidad')
    if idx_cad >= 0:
        for i in range(idx_cad, min(idx_cad + 2, len(lineas))):
            cad_match = re.search(r'(\d{8})', lineas[i])
            if cad_match:
                cad_str = cad_match.group(1)
                dia = cad_str[0:2]
                mes = cad_str[2:4]
                anio = cad_str[4:8]
                datos["fecha_caducidad"] = f"{dia}/{mes}/{anio}"
                break

    # ═══════════════════════════════════════════════════════
    # UBIGEO (REVERSO)
    # ═══════════════════════════════════════════════════════

    idx_depto = buscar_indice(r'Departamento|Depto')
    if idx_depto >= 0 and idx_depto + 1 < len(lineas):
        datos["departamento"] = lineas[idx_depto + 1]

    idx_prov = buscar_indice(r'Provincia')
    if idx_prov >= 0 and idx_prov + 1 < len(lineas):
        datos["provincia"] = lineas[idx_prov + 1]

    idx_dist = buscar_indice(r'Distrito')
    if idx_dist >= 0 and idx_dist + 1 < len(lineas):
        distrito = lineas[idx_dist + 1]
        if "-" in distrito:
            partes = distrito.split("-")
            if "provincia" not in datos:
                datos["provincia"] = partes[0].strip()
            datos["distrito"] = partes[1].strip()
        else:
            datos["distrito"] = distrito

    # ═══════════════════════════════════════════════════════
    # DIRECCIÓN (REVERSO)
    # ═══════════════════════════════════════════════════════

    idx_dir = buscar_indice(r'Direcci[oó]n')
    if idx_dir >= 0 and idx_dir + 1 < len(lineas):
        direccion = lineas[idx_dir + 1]
        if len(direccion) > 10:
            datos["direccion"] = direccion

    return datos


print("✅ Parser DNI v4.4 (estado civil corregido)")

# ═══════════════════════════════════════════════════════════════════════
# PARSER 2: CARNET DE EXTRANJERÍA
# ═══════════════════════════════════════════════════════════════════════

def parsear_carnet_extranjeria(texto_ocr):
    """
    Extrae campos del Carnet de Extranjería
    """
    import re
    datos = {}

    # ═══════════════════════════════════════════════════════
    # NÚMERO CE
    # ═══════════════════════════════════════════════════════
    ce_match = re.search(
        r'(?:N[°º]?|No\.?|CARNÉ DE EXTRANJERÍA)\s*(\d{9,10})',
        texto_ocr,
        re.IGNORECASE
    )
    if ce_match:
        datos["numero_ce"] = ce_match.group(1)
        datos["dni"] = ce_match.group(1)  # Para compatibilidad

    # ═══════════════════════════════════════════════════════
    # APELLIDOS
    # ═══════════════════════════════════════════════════════
    apellidos_match = re.search(
        r'Apellidos?[:\s]*\n?\s*([A-ZÑÁÉÍÓÚ\s]+)',
        texto_ocr,
        re.IGNORECASE
    )
    if apellidos_match:
        apellidos_completos = apellidos_match.group(1).strip()
        apellidos = apellidos_completos.split()

        if len(apellidos) >= 2:
            datos["apellido_paterno"] = apellidos[0]
            datos["apellido_materno"] = " ".join(apellidos[1:])
        else:
            datos["apellido_paterno"] = apellidos_completos

    # ═══════════════════════════════════════════════════════
    # NOMBRES
    # ═══════════════════════════════════════════════════════
    nombres_match = re.search(
        r'Nombr(?:e|es)?[:\s]*\n?\s*([A-ZÑÁÉÍÓÚ\s]+)',
        texto_ocr,
        re.IGNORECASE
    )
    if nombres_match:
        datos["nombres"] = nombres_match.group(1).strip()

    # Nombre completo
    if "nombres" in datos and "apellido_paterno" in datos:
        ap_mat = datos.get("apellido_materno", "")
        datos["nombre_completo"] = (
            f"{datos['nombres']} "
            f"{datos['apellido_paterno']} "
            f"{ap_mat}"
        ).strip()

    # ═══════════════════════════════════════════════════════
    # NACIONALIDAD
    # ═══════════════════════════════════════════════════════
    nac_match = re.search(
        r'Nacionalidad[:\s]*\n?\s*([A-ZÑÁÉÍÓÚ]+)',
        texto_ocr,
        re.IGNORECASE
    )
    if nac_match:
        datos["nacionalidad"] = nac_match.group(1).upper()

    # ═══════════════════════════════════════════════════════
    # FECHA DE NACIMIENTO (formato: 09 JUN 1990)
    # ═══════════════════════════════════════════════════════
    fnac_match = re.search(
        r'Fecha Nac[:\s]*(\d{2})\s*([A-Z]{3})\s*(\d{4})',
        texto_ocr,
        re.IGNORECASE
    )
    if fnac_match:
        dia, mes_txt, anio = fnac_match.groups()

        # Convertir mes texto → número
        MESES = {
            "ENE": "01", "FEB": "02", "MAR": "03", "ABR": "04",
            "MAY": "05", "JUN": "06", "JUL": "07", "AGO": "08",
            "SEP": "09", "SET": "09", "OCT": "10", "NOV": "11", "DIC": "12"
        }
        mes = MESES.get(mes_txt.upper(), "01")

        datos["fecha_nacimiento"] = f"{dia}/{mes}/{anio}"
        datos["fecha_nacimiento_iso"] = f"{anio}-{mes}-{dia}"

        # Calcular edad
        from datetime import datetime
        hoy = datetime.now()
        fecha_nac = datetime(int(anio), int(mes), int(dia))
        edad = (hoy - fecha_nac).days // 365
        datos["edad"] = edad

    # ═══════════════════════════════════════════════════════
    # SEXO
    # ═══════════════════════════════════════════════════════
    sexo_match = re.search(r'Sexo[:\s]*([MF])', texto_ocr, re.IGNORECASE)
    if sexo_match:
        datos["sexo"] = sexo_match.group(1).upper()
        datos["sexo_completo"] = "MASCULINO" if datos["sexo"] == "M" else "FEMENINO"

    # ═══════════════════════════════════════════════════════
    # CALIDAD MIGRATORIA
    # ═══════════════════════════════════════════════════════
    calidad_match = re.search(
        r'Calidad Migratoria[:\s]*([A-Z\s]+)',
        texto_ocr,
        re.IGNORECASE
    )
    if calidad_match:
        datos["calidad_migratoria"] = calidad_match.group(1).strip()

    # ═══════════════════════════════════════════════════════
    # UBIGEO (Departamento, Provincia, Distrito)
    # ═══════════════════════════════════════════════════════
    depto_match = re.search(
        r'Departamento[:\s]*\n?\s*([A-ZÑÁÉÍÓÚ\s]+)',
        texto_ocr,
        re.IGNORECASE
    )
    if depto_match:
        datos["departamento"] = depto_match.group(1).strip()

    prov_match = re.search(
        r'Provincia[:\s]*\n?\s*([A-ZÑÁÉÍÓÚ\s]+)',
        texto_ocr,
        re.IGNORECASE
    )
    if prov_match:
        datos["provincia"] = prov_match.group(1).strip()

    dist_match = re.search(
        r'Distrito[:\s]*\n?\s*([A-ZÑÁÉÍÓÚ\s]+)',
        texto_ocr,
        re.IGNORECASE
    )
    if dist_match:
        datos["distrito"] = dist_match.group(1).strip()

    # ═══════════════════════════════════════════════════════
    # DIRECCIÓN
    # ═══════════════════════════════════════════════════════
    dir_match = re.search(
        r'Direcci[oó]n[:\s]*\n?\s*([A-Z0-9\s\.,\-°º]+)',
        texto_ocr,
        re.IGNORECASE | re.MULTILINE
    )
    if dir_match:
        datos["direccion"] = dir_match.group(1).strip()

    return datos


print("✅ Parser de Carnet de Extranjería listo")

# ═══════════════════════════════════════════════════════════════════════
# PARSER 3: PASAPORTES
# ═══════════════════════════════════════════════════════════════════════

def parsear_pasaporte(texto_ocr):
    """
    Extrae campos de pasaportes (peruanos o extranjeros)
    Usa la zona MRZ (Machine Readable Zone) para máxima precisión
    """
    import re
    datos = {}

    # ═══════════════════════════════════════════════════════
    # MÉTODO 1: ZONA MRZ (más confiable)
    # ═══════════════════════════════════════════════════════

    # MRZ Línea 1: P<CODAPELLIDO<<NOMBRES<<<<<<<<<<<
    mrz_linea1 = re.search(
        r'P<([A-Z]{3})([A-Z<]+)<<([A-Z<]+)',
        texto_ocr
    )

    if mrz_linea1:
        codigo_pais = mrz_linea1.group(1)
        apellidos_mrz = mrz_linea1.group(2).replace("<", " ").strip()
        nombres_mrz = mrz_linea1.group(3).replace("<", " ").strip()

        datos["codigo_pais"] = codigo_pais
        datos["apellidos"] = apellidos_mrz
        datos["nombres"] = nombres_mrz
        datos["nombre_completo"] = f"{nombres_mrz} {apellidos_mrz}"

    # MRZ Línea 2: NUMERO123CODYYMMDDSFYYMMDD<<<<<<<<
    mrz_linea2 = re.search(
        r'(\w{9})(\d?)([A-Z]{3})(\d{2})(\d{2})(\d{2})([MF])(\d{2})(\d{2})(\d{2})',
        texto_ocr
    )

    if mrz_linea2:
        numero = mrz_linea2.group(1)
        pais = mrz_linea2.group(3)
        anio_nac = mrz_linea2.group(4)
        mes_nac = mrz_linea2.group(5)
        dia_nac = mrz_linea2.group(6)
        sexo = mrz_linea2.group(7)
        anio_venc = mrz_linea2.group(8)
        mes_venc = mrz_linea2.group(9)
        dia_venc = mrz_linea2.group(10)

        datos["numero_pasaporte"] = numero
        datos["dni"] = numero
        datos["sexo"] = sexo
        datos["sexo_completo"] = "MASCULINO" if sexo == "M" else "FEMENINO"

        # Convertir fechas YY → YYYY
        anio_nac_completo = f"19{anio_nac}" if int(anio_nac) > 25 else f"20{anio_nac}"
        anio_venc_completo = f"20{anio_venc}"

        datos["fecha_nacimiento"] = f"{dia_nac}/{mes_nac}/{anio_nac_completo}"
        datos["fecha_nacimiento_iso"] = f"{anio_nac_completo}-{mes_nac}-{dia_nac}"
        datos["fecha_vencimiento"] = f"{dia_venc}/{mes_venc}/{anio_venc_completo}"

        # Calcular edad
        from datetime import datetime
        hoy = datetime.now()
        fecha_nac = datetime(int(anio_nac_completo), int(mes_nac), int(dia_nac))
        edad = (hoy - fecha_nac).days // 365
        datos["edad"] = edad

    # ═══════════════════════════════════════════════════════
    # MÉTODO 2: TEXTO VISIBLE (complementario)
    # ═══════════════════════════════════════════════════════

    # Número de Pasaporte (si no se extrajo de MRZ)
    if "numero_pasaporte" not in datos:
        num_match = re.search(
            r'(?:Passport No|N[°º]? Pasaporte)[:\.\s]*([A-Z0-9]{7,9})',
            texto_ocr,
            re.IGNORECASE
        )
        if num_match:
            datos["numero_pasaporte"] = num_match.group(1)
            datos["dni"] = num_match.group(1)

    # Apellidos
    if "apellidos" not in datos:
        apellidos_match = re.search(
            r'(?:Surname|Apellidos?)[:\.\s]*\n?\s*([A-ZÑÁÉÍÓÚ\s]+)',
            texto_ocr,
            re.IGNORECASE
        )
        if apellidos_match:
            datos["apellidos"] = apellidos_match.group(1).strip()

    # Nombres
    if "nombres" not in datos:
        nombres_match = re.search(
            r'(?:Given Names?|Nombres?)[:\.\s]*\n?\s*([A-ZÑÁÉÍÓÚ\s]+)',
            texto_ocr,
            re.IGNORECASE
        )
        if nombres_match:
            datos["nombres"] = nombres_match.group(1).strip()

    # Nombre completo
    if "nombre_completo" not in datos:
        if "nombres" in datos and "apellidos" in datos:
            datos["nombre_completo"] = f"{datos['nombres']} {datos['apellidos']}"

    # Nacionalidad
    nac_match = re.search(
        r'(?:Nationality|Nacionalidad)[:\.\s]*\n?\s*([A-ZÑÁÉÍÓÚ\s]+)',
        texto_ocr,
        re.IGNORECASE
    )
    if nac_match:
        datos["nacionalidad"] = nac_match.group(1).strip()

    # Fecha de Nacimiento (si no se extrajo de MRZ)
    if "fecha_nacimiento" not in datos:
        fnac_match = re.search(
            r'(?:Date of Birth|Fecha de Nacimiento)[:\.\s]*(\d{2})\s*([A-Z]{3})\s*(\d{4})',
            texto_ocr,
            re.IGNORECASE
        )
        if fnac_match:
            dia, mes_txt, anio = fnac_match.groups()

            MESES = {
                "JAN": "01", "FEB": "02", "MAR": "03", "APR": "04",
                "MAY": "05", "JUN": "06", "JUL": "07", "AUG": "08",
                "SEP": "09", "OCT": "10", "NOV": "11", "DEC": "12"
            }
            mes = MESES.get(mes_txt.upper(), "01")

            datos["fecha_nacimiento"] = f"{dia}/{mes}/{anio}"
            datos["fecha_nacimiento_iso"] = f"{anio}-{mes}-{dia}"

    # Lugar de Nacimiento
    lugar_match = re.search(
        r'(?:Place of Birth|Lugar de Nacimiento)[:\.\s]*\n?\s*([A-ZÑÁÉÍÓÚ\s\-,]+)',
        texto_ocr,
        re.IGNORECASE
    )
    if lugar_match:
        datos["lugar_nacimiento"] = lugar_match.group(1).strip()

    # Fecha de Expedición
    emision_match = re.search(
        r'(?:Date of Issue|Fecha de Expedici[oó]n)[:\.\s]*(\d{2})\s*([A-Z]{3})\s*(\d{4})',
        texto_ocr,
        re.IGNORECASE
    )
    if emision_match:
        dia, mes_txt, anio = emision_match.groups()
        MESES = {
            "JAN": "01", "FEB": "02", "MAR": "03", "APR": "04",
            "MAY": "05", "JUN": "06", "JUL": "07", "AUG": "08",
            "SEP": "09", "OCT": "10", "NOV": "11", "DEC": "12"
        }
        mes = MESES.get(mes_txt.upper(), "01")
        datos["fecha_emision"] = f"{dia}/{mes}/{anio}"

    # Sexo (si no se extrajo de MRZ)
    if "sexo" not in datos:
        sexo_match = re.search(r'(?:Sex|Sexo)[:\.\s]*([MF])', texto_ocr, re.IGNORECASE)
        if sexo_match:
            datos["sexo"] = sexo_match.group(1).upper()
            datos["sexo_completo"] = "MASCULINO" if datos["sexo"] == "M" else "FEMENINO"

    return datos


print("✅ Parser de Pasaportes listo")

# ═══════════════════════════════════════════════════════════════════════
# FUNCIÓN PRINCIPAL: PROCESAR CUALQUIER DOCUMENTO
# ═══════════════════════════════════════════════════════════════════════

def procesar_documento(imagen_frente, imagen_reverso=None, mejorar_calidad=True):
    """
    FUNCIÓN MAESTRA que procesa cualquier documento peruano

    Workflow:
    1. Evalúa calidad de la imagen
    2. Mejora la imagen si es necesario (fotocopias)
    3. Aplica OCR
    4. Detecta tipo de documento
    5. Extrae datos específicos según el tipo
    6. Procesa reverso si es necesario
    7. Retorna datos estructurados

    Args:
        imagen_frente: str (ruta) o bytes (archivo)
        imagen_reverso: str (ruta) o bytes (archivo), opcional
        mejorar_calidad: bool - Si debe mejorar automáticamente la imagen

    Returns:
        dict: {
            "exito": bool,
            "tipo": str,
            "confianza": float,
            "necesita_reverso": bool,
            "datos": dict,
            "calidad_imagen": dict,
            "errores": list
        }
    """
    print("\n" + "=" * 70)
    print("🚀 INICIANDO PROCESAMIENTO DE DOCUMENTO")
    print("=" * 70)

    errores = []

    # ═══════════════════════════════════════════════════════
    # PASO 1: Cargar imagen del frente
    # ═══════════════════════════════════════════════════════
    print("\n📸 Cargando imagen del frente...")

    try:
        img_frente = cargar_imagen(imagen_frente)
        if img_frente is None:
            return {
                "exito": False,
                "error": "No se pudo cargar la imagen del frente",
                "errores": ["Imagen corrupta o formato no soportado"]
            }
        print(f"   ✅ Imagen cargada: {img_frente.shape[1]}x{img_frente.shape[0]} px")
    except Exception as e:
        return {
            "exito": False,
            "error": f"Error al cargar imagen: {str(e)}",
            "errores": [str(e)]
        }

    # ═══════════════════════════════════════════════════════
    # PASO 2: Evaluar calidad de la imagen
    # ═══════════════════════════════════════════════════════
    print("\n🔍 Evaluando calidad de imagen...")

    calidad = detectar_calidad_imagen(img_frente)

    print(f"   📊 Contraste: {calidad['contraste']:.1f}")
    print(f"   📊 Nitidez: {calidad['nitidez']:.1f}")
    print(f"   📊 Calidad: {calidad['calidad']}")

    if calidad['es_fotocopia']:
        print(f"   📄 Fotocopia detectada")

    # ═══════════════════════════════════════════════════════
    # PASO 3: Mejorar imagen si es necesario
    # ═══════════════════════════════════════════════════════
    if mejorar_calidad and calidad['calidad'] in ['REGULAR', 'MALA']:
        print("\n⚙️  Mejorando calidad de imagen...")
        img_procesada = mejorar_imagen_para_ocr(img_frente)
        print("   ✅ Imagen mejorada (contraste + nitidez)")
    else:
        img_procesada = img_frente
        print("\n✅ Imagen con calidad suficiente, no requiere mejora")

    # ═══════════════════════════════════════════════════════
    # PASO 4: Aplicar OCR al frente
    # ═══════════════════════════════════════════════════════
    print("\n🤖 Aplicando OCR al frente del documento...")

    try:
        resultado_ocr = ocr_engine.ocr(img_procesada, cls=True)
        texto_frente = extraer_texto_limpio(resultado_ocr)

        if not texto_frente:
            errores.append("No se detectó texto en la imagen")
            return {
                "exito": False,
                "error": "No se detectó texto legible",
                "errores": errores,
                "calidad_imagen": calidad
            }

        print(f"   ✅ OCR completado: {len(texto_frente)} caracteres extraídos")

    except Exception as e:
        errores.append(f"Error en OCR: {str(e)}")
        return {
            "exito": False,
            "error": "Error al aplicar OCR",
            "errores": errores
        }

    # ═══════════════════════════════════════════════════════
    # PASO 5: Detectar tipo de documento
    # ═══════════════════════════════════════════════════════
    print("\n🔍 Detectando tipo de documento...")

    deteccion = detectar_tipo_documento(texto_frente)

    if deteccion["tipo"] == "DESCONOCIDO":
        errores.append("No se pudo identificar el tipo de documento")
        print("\n❌ Tipo de documento no reconocido")
        print("\n📄 Texto extraído (primeros 500 caracteres):")
        print("-" * 70)
        print(texto_frente[:500])
        print("-" * 70)

        return {
            "exito": False,
            "error": "Tipo de documento no reconocido",
            "errores": errores,
            "texto_extraido": texto_frente,
            "calidad_imagen": calidad
        }

    mostrar_deteccion(deteccion)

    # ═══════════════════════════════════════════════════════
    # PASO 6: Parsear datos según el tipo
    # ═══════════════════════════════════════════════════════
    print("\n📝 Extrayendo datos del documento...")

    tipo = deteccion["tipo"]

    try:
        if tipo in ["DNI_AZUL", "DNI_ELECTRONICO"]:
            datos = parsear_dni(texto_frente, tipo)
        elif tipo == "CARNET_EXTRANJERIA":
            datos = parsear_carnet_extranjeria(texto_frente)
        elif tipo in ["PASAPORTE_PERUANO", "PASAPORTE_EXTRANJERO"]:
            datos = parsear_pasaporte(texto_frente)
        else:
            datos = {}

        print(f"   ✅ {len(datos)} campos extraídos del frente")

    except Exception as e:
        errores.append(f"Error al parsear datos: {str(e)}")
        datos = {}

    # ═══════════════════════════════════════════════════════
    # PASO 7: Procesar reverso si existe y es necesario
    # ═══════════════════════════════════════════════════════
    necesita_reverso = tipo in ["DNI_AZUL", "DNI_ELECTRONICO", "CARNET_EXTRANJERIA"]

    if imagen_reverso and necesita_reverso:
        print("\n📸 Procesando reverso del documento...")

        try:
            # Cargar imagen del reverso
            img_reverso = cargar_imagen(imagen_reverso)

            # Mejorar si es necesario
            if mejorar_calidad and calidad['calidad'] in ['REGULAR', 'MALA']:
                img_reverso = mejorar_imagen_para_ocr(img_reverso)

            # OCR del reverso
            resultado_ocr_rev = ocr_engine.ocr(img_reverso, cls=True)
            texto_reverso = extraer_texto_limpio(resultado_ocr_rev)

            # Parsear reverso
            if tipo in ["DNI_AZUL", "DNI_ELECTRONICO"]:
                datos_reverso = parsear_dni(texto_reverso, tipo)
            elif tipo == "CARNET_EXTRANJERIA":
                datos_reverso = parsear_carnet_extranjeria(texto_reverso)

            # COMBINAR datos (reverso complementa al frente)
            datos.update(datos_reverso)

            print(f"   ✅ Reverso procesado: {len(datos)} campos totales")

        except Exception as e:
            errores.append(f"Error al procesar reverso: {str(e)}")
            print(f"   ⚠️  Error al procesar reverso: {str(e)}")

    elif necesita_reverso and not imagen_reverso:
        print(f"\n⚠️  ADVERTENCIA: Este documento requiere foto del reverso")
        print("   Algunos campos pueden estar incompletos (ej: dirección)")

    # ═══════════════════════════════════════════════════════
    # PASO 8: Validar datos extraídos
    # ═══════════════════════════════════════════════════════
    print("\n✅ Validando datos extraídos...")

    campos_requeridos = ["nombre_completo", "dni", "fecha_nacimiento"]
    campos_faltantes = [c for c in campos_requeridos if c not in datos or not datos[c]]

    if campos_faltantes:
        print(f"   ⚠️  Campos faltantes: {', '.join(campos_faltantes)}")
        errores.append(f"Campos faltantes: {', '.join(campos_faltantes)}")
    else:
        print(f"   ✅ Todos los campos principales extraídos correctamente")

    # ═══════════════════════════════════════════════════════
    # PASO 9: Retornar resultado
    # ═══════════════════════════════════════════════════════
    exito = len(campos_faltantes) == 0

    print("\n" + "=" * 70)
    if exito:
        print("✅ PROCESAMIENTO COMPLETADO CON ÉXITO")
    else:
        print("⚠️  PROCESAMIENTO COMPLETADO CON ADVERTENCIAS")
    print("=" * 70)

    return {
        "exito": exito,
        "tipo": deteccion["tipo"],
        "formato": deteccion.get("formato"),
        "pais": deteccion.get("pais"),
        "confianza": deteccion["confianza"],
        "necesita_reverso": necesita_reverso,
        "datos": datos,
        "calidad_imagen": calidad,
        "errores": errores if errores else None,
        "texto_extraido": texto_frente  # Para debug
    }


print("✅ Función principal lista")

# ═══════════════════════════════════════════════════════════════════════
# VISUALIZACIÓN DE RESULTADOS
# ═══════════════════════════════════════════════════════════════════════

def mostrar_resultados(resultado):
    """
    Muestra los resultados del procesamiento de forma visual y organizada
    """
    print("\n" + "═" * 70)
    print("📊 RESULTADOS DEL PROCESAMIENTO")
    print("═" * 70)

    if not resultado["exito"]:
        print("\n❌ PROCESAMIENTO FALLIDO")
        if "error" in resultado:
            print(f"   Error: {resultado['error']}")
        if resultado.get("errores"):
            print("\n   Detalles:")
            for error in resultado["errores"]:
                print(f"   • {error}")
        return

    # ═══════════════════════════════════════════════════════
    # INFORMACIÓN DEL DOCUMENTO
    # ═══════════════════════════════════════════════════════
    print("\n📄 TIPO DE DOCUMENTO")
    print("-" * 70)
    print(f"   Tipo: {resultado['tipo'].replace('_', ' ')}")
    print(f"   País: {resultado.get('pais', 'N/A')}")
    print(f"   Confianza: {resultado['confianza']*100:.1f}%")

    # ═══════════════════════════════════════════════════════
    # DATOS PERSONALES
    # ═══════════════════════════════════════════════════════
    datos = resultado["datos"]

    print("\n👤 DATOS PERSONALES")
    print("-" * 70)

    if "nombre_completo" in datos:
        print(f"   Nombre Completo: {datos['nombre_completo']}")

    if "nombres" in datos:
        print(f"   Nombres: {datos['nombres']}")
    if "apellido_paterno" in datos:
        print(f"   Apellido Paterno: {datos['apellido_paterno']}")
    if "apellido_materno" in datos:
        print(f"   Apellido Materno: {datos['apellido_materno']}")

    # ═══════════════════════════════════════════════════════
    # DOCUMENTO DE IDENTIDAD
    # ═══════════════════════════════════════════════════════
    print("\n🆔 DOCUMENTO DE IDENTIDAD")
    print("-" * 70)

    if "dni" in datos:
        print(f"   DNI/Número: {datos['dni']}")
    if "cui" in datos:
        print(f"   CUI: {datos['cui']}")
    if "numero_ce" in datos:
        print(f"   N° CE: {datos['numero_ce']}")
    if "numero_pasaporte" in datos:
        print(f"   N° Pasaporte: {datos['numero_pasaporte']}")

    # ═══════════════════════════════════════════════════════
    # DATOS DEMOGRÁFICOS
    # ═══════════════════════════════════════════════════════
    print("\n📅 DATOS DEMOGRÁFICOS")
    print("-" * 70)

    if "fecha_nacimiento" in datos:
        print(f"   Fecha de Nacimiento: {datos['fecha_nacimiento']}")
    if "edad" in datos:
        print(f"   Edad: {datos['edad']} años")
    if "sexo_completo" in datos:
        print(f"   Sexo: {datos['sexo_completo']}")
    elif "sexo" in datos:
        print(f"   Sexo: {datos['sexo']}")
    if "nacionalidad" in datos:
        print(f"   Nacionalidad: {datos['nacionalidad']}")
    if "estado_civil" in datos:
        print(f"   Estado Civil: {datos['estado_civil']}")

    # ═══════════════════════════════════════════════════════
    # UBICACIÓN
    # ═══════════════════════════════════════════════════════
    if any(k in datos for k in ["departamento", "provincia", "distrito", "direccion"]):
        print("\n📍 UBICACIÓN")
        print("-" * 70)

        if "departamento" in datos:
            print(f"   Departamento: {datos['departamento']}")
        if "provincia" in datos:
            print(f"   Provincia: {datos['provincia']}")
        if "distrito" in datos:
            print(f"   Distrito: {datos['distrito']}")
        if "direccion" in datos:
            print(f"   Dirección: {datos['direccion']}")

    # ═══════════════════════════════════════════════════════
    # DATOS ADICIONALES
    # ═══════════════════════════════════════════════════════
    datos_adicionales = {}

    if "calidad_migratoria" in datos:
        datos_adicionales["Calidad Migratoria"] = datos["calidad_migratoria"]
    if "lugar_nacimiento" in datos:
        datos_adicionales["Lugar de Nacimiento"] = datos["lugar_nacimiento"]
    if "fecha_emision" in datos:
        datos_adicionales["Fecha de Emisión"] = datos["fecha_emision"]
    if "fecha_vencimiento" in datos:
        datos_adicionales["Fecha de Vencimiento"] = datos["fecha_vencimiento"]

    if datos_adicionales:
        print("\n📋 DATOS ADICIONALES")
        print("-" * 70)
        for key, value in datos_adicionales.items():
            print(f"   {key}: {value}")

    # ═══════════════════════════════════════════════════════
    # ADVERTENCIAS
    # ═══════════════════════════════════════════════════════
    if resultado.get("errores"):
        print("\n⚠️  ADVERTENCIAS")
        print("-" * 70)
        for error in resultado["errores"]:
            print(f"   • {error}")

    print("\n" + "═" * 70)


print("✅ Función de visualización lista")

# ═══════════════════════════════════════════════════════════════════════
# UTILIDAD: SUBIR ARCHIVOS EN COLAB
# ═══════════════════════════════════════════════════════════════════════

from google.colab import files
import io

def subir_imagenes():
    """
    Permite subir imágenes desde tu computadora a Colab

    Returns:
        dict: {
            "frente": bytes,
            "reverso": bytes (opcional)
        }
    """
    print("=" * 70)
    print("📤 SUBIR IMÁGENES")
    print("=" * 70)

    print("\n📸 Selecciona la foto del FRENTE del documento:")
    print("   (DNI/Pasaporte/Carnet de Extranjería)")

    uploaded_frente = files.upload()

    if not uploaded_frente:
        print("❌ No se subió ninguna imagen")
        return None

    # Obtener el archivo subido
    filename_frente = list(uploaded_frente.keys())[0]
    imagen_frente = io.BytesIO(uploaded_frente[filename_frente])

    print(f"✅ Frente subido: {filename_frente}")

    # Preguntar por el reverso
    print("\n¿Este documento necesita foto del reverso?")
    print("   • DNI (azul o electrónico) → SÍ")
    print("   • Carnet de Extranjería → SÍ")
    print("   • Pasaporte → NO")

    respuesta = input("\n¿Subir reverso? (s/n): ").strip().lower()

    imagen_reverso = None

    if respuesta == 's':
        print("\n📸 Selecciona la foto del REVERSO:")
        uploaded_reverso = files.upload()

        if uploaded_reverso:
            filename_reverso = list(uploaded_reverso.keys())[0]
            imagen_reverso = io.BytesIO(uploaded_reverso[filename_reverso])
            print(f"✅ Reverso subido: {filename_reverso}")

    return {
        "frente": imagen_frente,
        "reverso": imagen_reverso
    }


print("✅ Función de subida de archivos lista")

# ═══════════════════════════════════════════════════════════════════════
# EJEMPLOS DE USO
# ═══════════════════════════════════════════════════════════════════════

print("\n" + "=" * 70)
print("🎯 SISTEMA LISTO PARA USAR")
print("=" * 70)

print("\n📚 MODOS DE USO:\n")

print("🔹 OPCIÓN 1: Subir imágenes manualmente")
print("-" * 70)
print("""
# Ejecuta esta celda:
imagenes = subir_imagenes()

if imagenes:
    resultado = procesar_documento(
        imagen_frente=imagenes["frente"],
        imagen_reverso=imagenes["reverso"]
    )

    mostrar_resultados(resultado)
""")

print("\n🔹 OPCIÓN 2: Usar imágenes desde URL")
print("-" * 70)
print("""
# Descargar desde URL:
import urllib.request

url_frente = "https://ejemplo.com/dni_frente.jpg"
urllib.request.urlretrieve(url_frente, "dni_frente.jpg")

resultado = procesar_documento("dni_frente.jpg")
mostrar_resultados(resultado)
""")

print("\n🔹 OPCIÓN 3: Usar imágenes desde Google Drive")
print("-" * 70)
print("""
# 1) Montar Google Drive:
from google.colab import drive
drive.mount('/content/drive')

# 2) Procesar imagen desde Drive:
resultado = procesar_documento(
    imagen_frente="/content/drive/MyDrive/documentos/dni_frente.jpg",
    imagen_reverso="/content/drive/MyDrive/documentos/dni_reverso.jpg"
)

mostrar_resultados(resultado)
""")

print("\n🔹 OPCIÓN 4: Procesar múltiples documentos")
print("-" * 70)
print("""
# Procesar 3 personas (Padre, Madre, Menor):

documentos = {
    "padre": {
        "frente": "padre_frente.jpg",
        "reverso": "padre_reverso.jpg"
    },
    "madre": {
        "frente": "madre_frente.jpg",
        "reverso": "madre_reverso.jpg"
    },
    "menor": {
        "frente": "menor_frente.jpg",
        "reverso": "menor_reverso.jpg"
    }
}

resultados = {}

for persona, imgs in documentos.items():
    print(f"\\n{'='*70}")
    print(f"📄 Procesando: {persona.upper()}")
    print(f"{'='*70}")

    resultado = procesar_documento(
        imagen_frente=imgs["frente"],
        imagen_reverso=imgs["reverso"]
    )

    resultados[persona] = resultado
    mostrar_resultados(resultado)

# Ahora tienes todos los datos en 'resultados'
""")

print("\n" + "=" * 70)
print("💡 EJECUTA LA SIGUIENTE CELDA PARA EMPEZAR")
print("=" * 70)

# ═══════════════════════════════════════════════════════════════════════
# 🚀 DEMO INTERACTIVA - EJECUTA ESTA CELDA
# ═══════════════════════════════════════════════════════════════════════

print("🎬 INICIANDO DEMO INTERACTIVA\n")

# Subir imágenes
imagenes = subir_imagenes()

if imagenes:
    print("\n" + "🔄 " * 35)

    # Procesar documento
    resultado = procesar_documento(
        imagen_frente=imagenes["frente"],
        imagen_reverso=imagenes["reverso"],
        mejorar_calidad=True  # Mejorar automáticamente si es fotocopia
    )

    # Mostrar resultados
    mostrar_resultados(resultado)

    # ═══════════════════════════════════════════════════════
    # OPCIONES POST-PROCESAMIENTO
    # ═══════════════════════════════════════════════════════

    if resultado["exito"]:
        print("\n" + "=" * 70)
        print("✅ ¿QUÉ QUIERES HACER CON ESTOS DATOS?")
        print("=" * 70)

        print("\n1️⃣  Exportar como JSON")
        print("2️⃣  Exportar como CSV")
        print("3️⃣  Ver datos crudos (para debugging)")
        print("4️⃣  Guardar en variable para usar después")

        # Exportar como JSON
        import json

        json_output = json.dumps(resultado["datos"], indent=2, ensure_ascii=False)

        print("\n📄 DATOS EN FORMATO JSON:")
        print("-" * 70)
        print(json_output)

        # Guardar en variable global
        datos_extraidos = resultado["datos"]

        print("\n✅ Datos guardados en la variable: datos_extraidos")
        print("   Puedes acceder a ellos con: datos_extraidos['nombre_completo']")

else:
    print("\n❌ No se subieron imágenes")

# ═══════════════════════════════════════════════════════════════════════
# DEBUG: VER TEXTO RAW DEL OCR
# ═══════════════════════════════════════════════════════════════════════

from google.colab import files
import cv2
import numpy as np
from PIL import Image

print("📤 Sube la imagen del FRENTE:")
uploaded = files.upload()
imagen_path = list(uploaded.keys())[0]

# Cargar imagen
img = cv2.imread(imagen_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Aplicar OCR
resultado = ocr_engine.ocr(img_rgb, cls=True)

# Extraer SOLO el texto
texto_completo = []
for bloque in resultado[0]:
    texto = bloque[1][0]
    texto_completo.append(texto)

texto_raw = '\n'.join(texto_completo)

print("=" * 70)
print("📄 TEXTO RAW DEL OCR (línea por línea)")
print("=" * 70)
print(texto_raw)
print("=" * 70)

# Guardar en archivo para análisis
with open('texto_ocr.txt', 'w', encoding='utf-8') as f:
    f.write(texto_raw)

print("\n✅ Texto guardado en 'texto_ocr.txt'")
print("\n📋 Copia este texto y envíamelo para análisis")

# DEBUG REVERSO
from google.colab import files

print("📤 Sube la imagen del REVERSO (DNI02-523X250.jpg):")
uploaded = files.upload()
imagen_path = list(uploaded.keys())[0]

img = cv2.imread(imagen_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

resultado = ocr_engine.ocr(img_rgb, cls=True)

texto_completo = []
for bloque in resultado[0]:
    texto = bloque[1][0]
    texto_completo.append(texto)

texto_raw = '\n'.join(texto_completo)

print("=" * 70)
print("📄 TEXTO RAW DEL REVERSO")
print("=" * 70)
print(texto_raw)
print("=" * 70)

# ═══════════════════════════════════════════════════════════════════════
# CÓDIGO PARA INTEGRAR EN TU APP STREAMLIT
# ═══════════════════════════════════════════════════════════════════════

codigo_streamlit = '''
# ═══════════════════════════════════════════════════════════════════════
# INTEGRACIÓN EN app.py (tu sistema actual)
# ═══════════════════════════════════════════════════════════════════════

import streamlit as st
from paddleocr import PaddleOCR
import cv2
import numpy as np

# Inicializar OCR (una sola vez, al inicio de la app)
@st.cache_resource
def cargar_ocr():
    return PaddleOCR(use_angle_cls=True, lang="es", use_gpu=False)

ocr_engine = cargar_ocr()

# ═══════════════════════════════════════════════════════════════════════
# EN TU FORMULARIO DE PERMISOS
# ═══════════════════════════════════════════════════════════════════════

st.subheader("👨 Datos del Padre")

# Pestañas para elegir método
tab_ocr, tab_manual = st.tabs(["📸 Escanear DNI", "⌨️ Ingresar manualmente"])

with tab_ocr:
    st.caption("Sube fotos o fotocopias del DNI (ambos lados)")

    col1, col2 = st.columns(2)

    with col1:
        padre_frente = st.file_uploader(
            "Frente del DNI",
            type=["jpg", "jpeg", "png"],
            key="padre_frente"
        )
        if padre_frente:
            st.image(padre_frente, caption="Vista previa", width=200)

    with col2:
        padre_reverso = st.file_uploader(
            "Reverso del DNI",
            type=["jpg", "jpeg", "png"],
            key="padre_reverso"
        )
        if padre_reverso:
            st.image(padre_reverso, caption="Vista previa", width=200)

    if st.button("🔍 Extraer datos automáticamente", key="btn_padre"):
        if padre_frente:
            with st.spinner("Procesando documento..."):
                # AQUÍ LLAMAS A TU FUNCIÓN procesar_documento()
                resultado = procesar_documento(
                    imagen_frente=padre_frente,
                    imagen_reverso=padre_reverso
                )

                if resultado["exito"]:
                    st.success(f"✅ Documento procesado: {resultado['tipo']}")

                    # PRE-LLENAR CAMPOS DEL FORMULARIO
                    datos = resultado["datos"]

                    st.session_state["padre_nombre"] = datos.get("nombre_completo", "")
                    st.session_state["padre_dni"] = datos.get("dni", "")
                    st.session_state["padre_fnac"] = datos.get("fecha_nacimiento", "")
                    st.session_state["padre_sexo"] = datos.get("sexo", "")
                    st.session_state["padre_departamento"] = datos.get("departamento", "")
                    st.session_state["padre_provincia"] = datos.get("provincia", "")
                    st.session_state["padre_distrito"] = datos.get("distrito", "")
                    st.session_state["padre_direccion"] = datos.get("direccion", "")

                    st.rerun()  # Recargar para mostrar campos pre-llenados

                else:
                    st.error(f"❌ {resultado['error']}")
                    st.info("💡 Intenta con mejor calidad de imagen o usa ingreso manual")
        else:
            st.warning("⚠️ Debes subir al menos la foto del frente")

with tab_manual:
    # Tu formulario actual (sin cambios)
    padre_nombre = st.text_input(
        "Nombre completo del padre",
        value=st.session_state.get("padre_nombre", "")
    )
    padre_dni = st.text_input(
        "DNI del padre",
        value=st.session_state.get("padre_dni", "")
    )
    # ... resto de campos

# ═══════════════════════════════════════════════════════════════════════
# REPETIR LO MISMO PARA MADRE Y MENOR
# ═══════════════════════════════════════════════════════════════════════
'''

print("=" * 70)
print("💻 CÓDIGO PARA INTEGRAR EN TU STREAMLIT")
print("=" * 70)
print(codigo_streamlit)

# Guardar en archivo
with open("integracion_streamlit.py", "w", encoding="utf-8") as f:
    f.write(codigo_streamlit)

print("\n✅ Código guardado en: integracion_streamlit.py")
print("   Puedes descargarlo y copiarlo a tu app.py")

# ═══════════════════════════════════════════════════════════════════════
# ANALIZAR RENDIMIENTO Y PRECISIÓN
# ═══════════════════════════════════════════════════════════════════════

def generar_reporte(resultados_lista):
    """
    Genera reporte de múltiples procesamientos

    Args:
        resultados_lista: list de resultados de procesar_documento()
    """
    print("\n" + "=" * 70)
    print("📊 REPORTE DE PROCESAMIENTO")
    print("=" * 70)

    total = len(resultados_lista)
    exitosos = sum(1 for r in resultados_lista if r["exito"])
    fallidos = total - exitosos

    print(f"\n📈 RESUMEN GENERAL")
    print("-" * 70)
    print(f"   Total procesados: {total}")
    print(f"   ✅ Exitosos: {exitosos} ({exitosos/total*100:.1f}%)")
    print(f"   ❌ Fallidos: {fallidos} ({fallidos/total*100:.1f}%)")

    # Tipos de documentos
    tipos = {}
    for r in resultados_lista:
        if r.get("tipo"):
            tipo = r["tipo"]
            tipos[tipo] = tipos.get(tipo, 0) + 1

    print(f"\n📄 TIPOS DE DOCUMENTOS")
    print("-" * 70)
    for tipo, count in tipos.items():
        print(f"   {tipo.replace('_', ' ')}: {count}")

    # Confianza promedio
    confianzas = [r["confianza"] for r in resultados_lista if "confianza" in r]
    if confianzas:
        promedio = sum(confianzas) / len(confianzas)
        print(f"\n🎯 CONFIANZA PROMEDIO: {promedio*100:.1f}%")

    # Calidad de imágenes
    calidades = [r["calidad_imagen"]["calidad"] for r in resultados_lista if "calidad_imagen" in r]
    if calidades:
        print(f"\n📸 CALIDAD DE IMÁGENES")
        print("-" * 70)
        from collections import Counter
        conteo = Counter(calidades)
        for calidad, count in conteo.items():
            print(f"   {calidad}: {count}")


print("✅ Función de reportes lista")